package com.example.br3

data class Item(
    val reference: String,
    val pairs: String,
    val color: String,
    var childrensUnitaryValue: String,
    var adultUnitaryValue: String,
    var amountNumber20: String,
    var amountNumber21: String,
    var amountNumber22: String,
    var amountNumber23: String,
    var amountNumber24: String,
    var amountNumber25: String,
    var amountNumber26: String,
    var amountNumber27: String,
    var amountNumber28: String,
    var amountNumber29: String,
    var amountNumber30: String,
    var amountNumber31: String,
    var amountNumber32: String,
    var amountNumber33: String,
    var amountNumber34: String,
    var amountNumber35: String,
    var amountNumber36: String,
    var amountNumber37: String,
    var amountNumber38: String,
    var amountNumber39: String,
    var amountNumber40: String,
    var amountNumber41: String,
    var amountNumber42: String,
    var amountNumber43: String,
    var amountNumber44: String,
    var amountNumber45: String,
    var amountNumber46: String,
    )
