package com.example.br3

data class Item(
    val reference: String,
    val pairs: String,
    val color: String,
    val amountNumber20: String,
    val amountNumber21: String,
    val amountNumber22: String,
    val amountNumber23: String,
    val amountNumber24: String,
    val amountNumber25: String,
    val amountNumber26: String,
    val amountNumber27: String,
    val amountNumber28: String,
    val amountNumber29: String,
    val amountNumber30: String,
    val amountNumber31: String,
    val amountNumber32: String,
    val amountNumber33: String,
    val amountNumber34: String,
    val amountNumber35: String,
    val amountNumber36: String,
    val amountNumber37: String,
    val amountNumber38: String,
    val amountNumber39: String,
    val amountNumber40: String,
    val amountNumber41: String,
    val amountNumber42: String,
    val amountNumber43: String,
    val amountNumber44: String,
    val amountNumber45: String,
    val amountNumber46: String,

)
